[package]
name = "crux_http"
description = "HTTP capability for use with crux_core"
version = "0.9.1"
readme = "README.md"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[features]
default = ["encoding"]
# requires web-sys for TextDecoder on wasm
encoding = ["encoding_rs", "web-sys"]

[dependencies]
anyhow.workspace = true
async-trait = "0.1.80"
crux_core = { version = "0.7", path = "../crux_core" }
derive_builder = "0.20.0"
futures-util = "0.3"
http-types = { package = "http-types-red-badger-temporary-fork", version = "2.12.0", default-features = false }
pin-project-lite = "0.2.14"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.60"
url = "2.5.0"
encoding_rs = { version = "0.8.20", optional = true }
web-sys = { optional = true, version = "0.3.25", features = ["TextDecoder"] }

[dev-dependencies]
assert_fs = "1.0.13"
futures-test = "0.3"
assert_matches = "1.5"
